### ISSUE TITLE
Pre-built version or build instructions?

### ISSUE THREAD

**Issue by nevkontakte** [noggaholic/bugcraft-studio#1]
Hi! Your tool seems to be what I'm looking for for my wow video projects. However, I'm unfamiliar with Electron and frameworks you use. Could you please provide either build instructions or a pre-built version?

Thanks!

**Comment by karliky** [comment]
Hey nevkontakte,

Thank you for your interest on this tool. I'm preparing a talk about reverse engineering games and don't have time to work on this until I finish so no binaries will be available until that. Maybe January/February of 2018.

I'll keep this open and will inform you on any progress.

Thank you

**Comment by kennybaby** [comment]
NEED IT PLZ！
It's seems cool for my wow video "wow 1.12.1".
Could you please provide either build instructions or a pre-built version?

Thanks!

**Comment by karliky** [comment]
https://github.com/noggaholic/bugcraft-studio/releases/tag/1.0.0
