### ISSUE TITLE
[Update] For 64-bit Client

### ISSUE THREAD

**Issue by Smoodi** [noggaholic/bugcraft-studio#14]
Ever since the discontinuation of the 32-bit client the tool sadly won't work anymore.
Hence I'm asking if there are any plans on adding a 64-bit compatibility.
Especially for clients like BfA Client 8.3.7.

I sadly have little experience with reverse-engineering programs like this, it'd be sad to see a project like this being discontinued though. :/

**Comment by karliky** [comment]
Hey Smoodi,

First of all, thanks for being a BugCraft Studio user.

The purpose of BugCraft Studio is to support any x86 version and to provide the same functionality across versions.

From the 7.3.5 version and so on, the process wow.exe introduces several different security features that require to bypass some complex security logic. That's something I don't want to do for now, I prefer to focus on the x86 version and move to x64 when I'm done with that. That will take some years for sure. This is a long term project.

Can you tell me what's so special about BfA Client 8.3.7.?

**Comment by Smoodi** [comment]
Hi,
Thank you for the quick response.
I named the BfA Client 8.3.7 only because I've tried some testing on it myself using memory tools, trying to get similar results as with the tool in previous versions. Sadly without any success, that's all. ^^
Thank you for the quick and kind response. ^^

**Comment by karliky** [comment]
Another concern is that people may try to modify the tool to make it work in retail. which I don't want to as I respect Blizzard's work, I don't think this tool should work in retail, anyway, I guess BugCraft Studio will work for BFA _some day_

**Comment by Smoodi** [comment]
That's fair ^^ - I respect that ^^
